SUBROUTINE URDFIL(LSTOP,LOVRWRT,KSTEP,KINC,DTIME,TIME)

    INCLUDE 'ABA_PARAM.INC'

    DIMENSION ARRAY(513),JRRAY(NPRECD,513),TIME(2)
    EQUIVALENCE (ARRAY(1),JRRAY(1,1))
    PARAMETER(TOL=2.09D8)

! FIND CURRENT INCREMENT.

    CALL POSFIL(KSTEP,KINC,ARRAY,JRCD)
    DO K1=1,999999
        CALL DBFILE(0,ARRAY,JRCD)
        IF (JRCD .NE. 0) GO TO 110
        KEY=JRRAY(1,2)

! RECORD 12 CONTAINS VALUES FOR SINV

        IF (KEY.EQ.12) THEN
            IF (ARRAY(3).GT.TOL) THEN
                LSTOP=1
                GO TO 110
            END IF
        END IF
    END DO
 110  CONTINUE
C
      RETURN
      END