SUBROUTINE UMAT(STRESS,STATEV,DDSDDE,SSE,SPD,SCD, &
    RPL,DDSDDT,DRPLDE,DRPLDT, &
    STRAN,DSTRAN,TIME,DTIME,TEMP,DTEMP,PREDEF,DPRED,CMNAME, &
    NDI,NSHR,NTENS,NSTATV,PROPS,NPROPS,COORDS,DROT,PNEWDT, &
    CELENT,DFGRD0,DFGRD1,NOEL,NPT,LAYER,KSPT,JSTEP,KINC)

    INCLUDE 'ABA_PARAM.INC'

    CHARACTER*80 CMNAME
    DIMENSION STRESS(NTENS),STATEV(NSTATV), &
        DDSDDE(NTENS,NTENS),DDSDDT(NTENS),DRPLDE(NTENS), &
        STRAN(NTENS),DSTRAN(NTENS),TIME(2),PREDEF(1),DPRED(1), &
        PROPS(NPROPS),COORDS(3),DROT(3,3),DFGRD0(3,3),DFGRD1(3,3), &
        JSTEP(4)


    ! user coding to define DDSDDE, STRESS, STATEV, SSE, SPD, SCD
    ! and, if necessary, RPL, DDSDDT, DRPLDE, DRPLDT, PNEWDT


    RETURN
    ! Iteration ends here
    END