SUBROUTINE UMATHT(U,DUDT,DUDG,FLUX,DFDT,DFDG, &
                STATEV,TEMP,DTEMP,DTEMDX,TIME,DTIME,PREDEF,DPRED, &
                CMNAME,NTGRD,NSTATV,PROPS,NPROPS,COORDS,PNEWDT, &
                NOEL,NPT,LAYER,KSPT,KSTEP,KINC)

    INCLUDE 'ABA_PARAM.INC'

    CHARACTER*80 CMNAME
    DIMENSION DUDG(NTGRD),FLUX(NTGRD),DFDT(NTGRD), &
        DFDG(NTGRD,NTGRD),STATEV(NSTATV),DTEMDX(NTGRD), &
        TIME(2),PREDEF(1),DPRED(1),PROPS(NPROPS),COORDS(3)

    ! user coding to define U,DUDT,DUDG,FLUX,DFDT,DFDG,
    ! and possibly update STATEV, PNEWDT

    RETURN
    END