      CHARACTER*80 CPNAME
      ...
      CALL GETPARTINFO(INTNUM, JTYP, CPNAME, LOCNUM, JRCD)
      or
      CALL VGETPARTINFO(INTNUM, JTYP, CPNAME, LOCNUM, JRCD)


      CHARACTER*80 CPNAME
      ...
      CALL GETINTERNAL(CPNAME, LOCNUM, JTYP, INTNUM, JRCD)
      or 
      CALL VGETINTERNAL(CPNAME, LOCNUM, JTYP, INTNUM, JRCD)