SUBROUTINE GETVRM_MF(VAR,KPHASE,JPHASE2MAT,ARRAY,JARRAY,FLGRAY,
1 JRCD,JMAC,JMATYP,SECLAYO,LACCFLG)
C
INCLUDE 'ABA_PARAM.INC'
C
DIMENSION ARRAY(15), JARRAY(15)
CHARACTER*3 FLGRAY(15)

user coding to obtain values of  VAR


RETURN
END